# Generated by Django 3.1.2 on 2021-09-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0002_birthday_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='username',
            new_name='created_by',
        ),
    ]
